import { Accordion } from "@/components/ui/Accordion";

const FAQ_ITEMS = [
	{
		question: "Does this tool use AI to explain the expression?",
		answer: "No. The explanation is generated by deterministic parsing logic that reads each field and applies the same rules every time — the same input always produces the same output, with no external calls.",
	},
	{
		question: "Why does my explanation say \"or\" between the day-of-month and day-of-week parts?",
		answer: "That's standard cron behavior: when both the day-of-month and day-of-week fields are restricted (not *), the job runs if either condition is true, not only when both match on the same day.",
	},
	{
		question: "What timezone are the \"next run times\" shown in?",
		answer: "Your browser's local timezone. Cron itself doesn't store a timezone — the actual server or scheduler running the job determines what timezone \"9:00 AM\" means in practice.",
	},
	{
		question: "Why couldn't it find any upcoming run times?",
		answer: "The next-run calculation searches up to a year ahead before giving up. An expression that only matches a very rare calendar combination (like day 31 in a field that also restricts to specific months without 31 days) may not have a match in that window.",
	},
];

export function CronParserFaq() {
	return (
		<section id="faq" className="scroll-mt-16 border-t border-border">
			<div className="container mx-auto max-w-3xl px-4 py-16">
				<h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Frequently asked questions</h2>

				<div className="mt-8">
					<Accordion items={FAQ_ITEMS} />
				</div>
			</div>
		</section>
	);
}
